import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

spatial_triples = [
    # Bohai Sea
    ("Bohai Sea", "lat_range", "37°23'N-41°23'N"),
    ("Bohai Sea", "lon_range", "117°43'E-121°21'E"),
    ("Bohai Sea", "type", "semi-enclosed inland sea"),
    ("Bohai Sea", "surrounded_by", "China"),
    ("Bohai Sea", "north", "Liaoning"),
    ("Bohai Sea", "west", "Tianjin, Hebei"),
    ("Bohai Sea", "south", "Shandong"),
    ("Bohai Sea", "connected_to", "Yellow Sea via Bohai Strait"),
    ("Bohai Strait", "width", "76 km"),
    ("Bohai Strait", "narrowest_point", "Chengshanjiao-Laotieshan"),
    ("Bohai Strait", "narrowest_width", "34 km"),
    # Yellow Sea
    ("Yellow Sea", "lat_range", "30°20'N-38°43'N"),
    ("Yellow Sea", "lon_range", "119°30'E-126°18'E"),
    ("Yellow Sea", "type", "semi-enclosed marginal sea"),
    ("Yellow Sea", "east_coast", "Shandong, Jiangsu"),
    ("Yellow Sea", "west_coast", "South Korea, North Korea"),
    ("Yellow Sea", "connected_to", "Bohai Sea via Shandong Peninsula"),
    ("Yellow Sea", "connected_to", "East China Sea via Yangtze Estuary"),
    # East China Sea
    ("East China Sea", "lat_range", "22°42'N-33°33'N"),
    ("East China Sea", "lon_range", "118°50'E-127°44'E"),
    ("East China Sea", "type", "marginal sea"),
    ("East China Sea", "north_coast", "Yangtze Estuary, Zhejiang"),
    ("East China Sea", "east_coast", "Kyushu, Ryukyu Islands"),
    ("East China Sea", "south_coast", "Fujian, Taiwan"),
    ("East China Sea", "connected_to", "South China Sea via Taiwan Strait"),
    ("East China Sea", "connected_to", "Yellow Sea via Yangtze Estuary"),
    # River Estuaries
    ("Yellow River Estuary", "lat_lon", "37°24'N, 118°52'E"),
    ("Yellow River Estuary", "location", "Dongying, Shandong"),
    ("Yellow River Estuary", "flows_into", "Bohai Sea"),
    ("Liao River Estuary", "lat_lon", "40°38'N, 121°53'E"),
    ("Liao River Estuary", "location", "Panjin, Liaoning"),
    ("Liao River Estuary", "flows_into", "Bohai Sea"),
    ("Yalu River Estuary", "lat_lon", "39°58'N, 124°15'E"),
    ("Yalu River Estuary", "location", "Dandong, Liaoning-Sinuiju, North Korea"),
    ("Yalu River Estuary", "flows_into", "Yellow Sea"),
    ("Huai River Estuary", "lat_lon", "33°07'N, 119°53'E"),
    ("Huai River Estuary", "location", "Huai'an, Jiangsu"),
    ("Huai River Estuary", "flows_into", "Yellow Sea"),
    ("Yangtze River Estuary", "lat_lon", "31°26'N, 121°13'E"),
    ("Yangtze River Estuary", "location", "Jiangsu-Shanghai border"),
    ("Yangtze River Estuary", "flows_into", "East China Sea"),
    ("Qiantang River Estuary", "lat_lon", "30°12'N, 120°52'E"),
    ("Qiantang River Estuary", "location", "Hangzhou, Zhejiang"),
    ("Qiantang River Estuary", "flows_into", "East China Sea"),
    ("Min River Estuary", "lat_lon", "26°00'N, 119°28'E"),
    ("Min River Estuary", "location", "Fuzhou, Fujian"),
    ("Min River Estuary", "flows_into", "East China Sea"),
    ("Pearl River Estuary", "lat_lon", "22°47'N, 113°36'E"),
    ("Pearl River Estuary", "location", "Guangzhou, Guangdong"),
    ("Pearl River Estuary", "flows_into", "South China Sea"),
    # Chl-a
    ("Chl-a", "related_to", "SST"),
    ("Chl-a", "higher_in", "moderate SST"),
    ("high_low_temp", "inhibits", "phytoplankton"),
    ("Chl-a", "related_to", "PIC"),
    ("PIC", "positively_correlated", "Chl-a"),
    ("high_nutrients", "promotes", "phytoplankton"),
    ("phytoplankton", "increases", "inorganic_carbon"),
    ("Chl-a", "related_to", "POC"),
    ("Chl-a", "positively_correlated", "POC"),
    ("phytoplankton", "affects", "organic_carbon"),
    ("Chl-a", "related_to", "PAR"),
    ("PAR", "drives", "phytoplankton_photosynthesis"),
    ("Chl-a", "positively_correlated", "PAR"),
    ("Chl-a", "related_to", "NFLH"),
    ("NFLH", "reflects", "Chl-a_fluorescence"),
    ("NFLH", "positively_correlated", "Chl-a"),
    ("high_Chl-a", "increases", "fluorescence"),
    # Spatial Distribution
    ("Chl-a", "higher_in", "coastal"),
    ("Chl-a", "decreases", "offshore"),
    ("Chl-a", "higher_in", "enclosed_seas"),
    ("Chl-a", "trend", "Bohai > Yellow Sea > East China Sea"),
    ("Yellow Sea", "high_Chl-a", "unique_water_env"),
    ("Bohai Sea", "rich_nutrients", "land_influence"),
    ("Bohai Sea", "high_Chl-a", "small_size"),
    ("East China Sea", "uniform_nutrients", "open_water"),
    ("East China Sea", "high_Chl-a", "southern_coast, Taiwan Strait"),
    ("Yellow River Estuary", "high_Chl-a", "rich_nutrients"),
    ("Yangtze River Estuary", "high_Chl-a", "rich_nutrients"),
    ("Pearl River Estuary", "high_Chl-a", "rich_nutrients"),
    # Other Elements
    ("SST", "influenced_by", "river_discharge, coastal_currents"),
    ("SST", "lower_in", "coastal"),
    ("SST", "higher_in", "offshore"),
    ("SST", "trend", "coast_to_offshore_increase"),
    ("PIC", "higher_in", "coastal"),
    ("PIC", "decreases", "offshore"),
    ("POC", "higher_in", "coastal"),
    ("POC", "decreases", "offshore"),
    ("PAR", "lower_in", "coastal"),
    ("PAR", "higher_in", "offshore"),
    ("NFLH", "stronger_in", "coastal"),
    ("NFLH", "weakens", "offshore"),
    ("marine_elements", "active_in", "coastal"),
    ("marine_elements", "decrease", "offshore"),
]
# 时间相关的三元组
temporal_triples = [
    ("Chl-a", "concentration_spring", "high"),
    ("Chl-a", "concentration_summer", "low"),
    ("Chl-a", "concentration_autumn", "increase"),
    ("Chl-a", "concentration_winter", "low"),

    ("Chl-a", "concentration_march", "increase"),
    ("Chl-a", "concentration_april", "increase"),
    ("Chl-a", "concentration_july", "low"),
    ("Chl-a", "concentration_august", "low"),
    ("Chl-a", "concentration_september", "high"),
    ("Chl-a", "concentration_october", "high"),
    ("Chl-a", "concentration_january", "low"),
    ("Chl-a", "concentration_february", "low"),

    ("SST", "variation_spring", "rising"),
    ("SST", "variation_summer", "highest"),
    ("SST", "variation_autumn", "decreasing"),
    ("SST", "variation_winter", "lowest"),

    ("PIC", "variation_spring", "rising"),
    ("PIC", "variation_summer", "decreasing"),
    ("PIC", "variation_autumn", "increasing"),
    ("PIC", "variation_winter", "lowest"),

    ("POC", "variation_spring", "rising"),
    ("POC", "variation_summer", "decreasing"),
    ("POC", "variation_autumn", "increasing"),
    ("POC", "variation_winter", "lowest"),

    ("PAR", "variation_spring", "strengthening"),
    ("PAR", "variation_summer", "highest"),
    ("PAR", "variation_autumn", "weakening"),
    ("PAR", "variation_winter", "lowest"),

    ("NFLH", "variation_spring", "strengthening"),
    ("NFLH", "variation_summer", "low"),
    ("NFLH", "variation_autumn", "strengthening"),
    ("NFLH", "variation_winter", "lowest"),

    ("kuroshio", "strength_spring", "strengthening"),
    ("kuroshio", "strength_summer", "strongest"),
    ("kuroshio", "strength_autumn", "weakening"),
    ("kuroshio", "strength_winter", "weakest"),

    ("coastal_current", "strength_spring", "active"),
    ("coastal_current", "strength_summer", "weakening"),
    ("coastal_current", "strength_autumn", "strengthening"),
    ("coastal_current", "strength_winter", "stable"),

    ("seasonal_circulation", "strength_spring", "stable"),
    ("seasonal_circulation", "strength_summer", "seaward"),
    ("seasonal_circulation", "strength_autumn", "northeast"),
    ("seasonal_circulation", "strength_winter", "shoreward"),

    ("coastal_current", "impact_spring", "promote_Chl-a"),
    ("coastal_current", "impact_autumn", "promote_Chl-a"),
    ("kuroshio", "impact_summer", "inhibit_Chl-a"),
    ("seaward_circulation", "impact_summer", "inhibit_Chl-a"),
    ("shoreward_circulation", "impact_winter", "inhibit_Chl-a"),

    ("Chl-a", "concentration_spring", "rising"),
    ("Chl-a", "concentration_summer", "low"),
    ("Chl-a", "concentration_autumn", "rising"),
    ("Chl-a", "concentration_winter", "low")
]

myself_triples = [
    ("Chl-a", "concentration_spring", "high"),
    ("Chl-a", "concentration_summer", "low"),
    ("Chl-a", "concentration_autumn", "increase"),
    ("Chl-a", "concentration_winter", "low"),

    ("Chl-a", "concentration_march", "increase"),
    ("Chl-a", "concentration_april", "increase"),
    ("Chl-a", "concentration_july", "low"),
    ("Chl-a", "concentration_august", "low"),
    ("Chl-a", "concentration_september", "high"),
    ("Chl-a", "concentration_october", "high"),
    ("Chl-a", "concentration_january", "low"),
    ("Chl-a", "concentration_february", "low"),

    ("SST", "variation_spring", "rising"),
    ("SST", "variation_summer", "highest"),
    ("SST", "variation_autumn", "decreasing"),
    ("SST", "variation_winter", "lowest"),

    ("PIC", "variation_spring", "rising"),
    ("PIC", "variation_summer", "decreasing"),
    ("PIC", "variation_autumn", "increasing"),
    ("PIC", "variation_winter", "lowest"),

    ("POC", "variation_spring", "rising"),
    ("POC", "variation_summer", "decreasing"),
    ("POC", "variation_autumn", "increasing"),
    ("POC", "variation_winter", "lowest"),

    ("PAR", "variation_spring", "strengthening"),
    ("PAR", "variation_summer", "highest"),
    ("PAR", "variation_autumn", "weakening"),
    ("PAR", "variation_winter", "lowest"),

    ("NFLH", "variation_spring", "strengthening"),
    ("NFLH", "variation_summer", "low"),
    ("NFLH", "variation_autumn", "strengthening"),
    ("NFLH", "variation_winter", "lowest"),

    ("kuroshio", "strength_spring", "strengthening"),
    ("kuroshio", "strength_summer", "strongest"),
    ("kuroshio", "strength_autumn", "weakening"),
    ("kuroshio", "strength_winter", "weakest"),

    ("coastal_current", "strength_spring", "active"),
    ("coastal_current", "strength_summer", "weakening"),
    ("coastal_current", "strength_autumn", "strengthening"),
    ("coastal_current", "strength_winter", "stable"),

    ("seasonal_circulation", "strength_spring", "stable"),
    ("seasonal_circulation", "strength_summer", "seaward"),
    ("seasonal_circulation", "strength_autumn", "northeast"),
    ("seasonal_circulation", "strength_winter", "shoreward"),

    ("coastal_current", "impact_spring", "promote_Chl-a"),
    ("coastal_current", "impact_autumn", "promote_Chl-a"),
    ("kuroshio", "impact_summer", "inhibit_Chl-a"),
    ("seaward_circulation", "impact_summer", "inhibit_Chl-a"),
    ("shoreward_circulation", "impact_winter", "inhibit_Chl-a"),

    ("Chl-a", "concentration_spring", "rising"),
    ("Chl-a", "concentration_summer", "low"),
    ("Chl-a", "concentration_autumn", "rising"),
    ("Chl-a", "concentration_winter", "low"),
    # Bohai Sea
    ("Bohai Sea", "lat_range", "37°23'N-41°23'N"),
    ("Bohai Sea", "lon_range", "117°43'E-121°21'E"),
    ("Bohai Sea", "type", "semi-enclosed inland sea"),
    ("Bohai Sea", "surrounded_by", "China"),
    ("Bohai Sea", "north", "Liaoning"),
    ("Bohai Sea", "west", "Tianjin, Hebei"),
    ("Bohai Sea", "south", "Shandong"),
    ("Bohai Sea", "connected_to", "Yellow Sea via Bohai Strait"),
    ("Bohai Strait", "width", "76 km"),
    ("Bohai Strait", "narrowest_point", "Chengshanjiao-Laotieshan"),
    ("Bohai Strait", "narrowest_width", "34 km"),
    # Yellow Sea
    ("Yellow Sea", "lat_range", "30°20'N-38°43'N"),
    ("Yellow Sea", "lon_range", "119°30'E-126°18'E"),
    ("Yellow Sea", "type", "semi-enclosed marginal sea"),
    ("Yellow Sea", "east_coast", "Shandong, Jiangsu"),
    ("Yellow Sea", "west_coast", "South Korea, North Korea"),
    ("Yellow Sea", "connected_to", "Bohai Sea via Shandong Peninsula"),
    ("Yellow Sea", "connected_to", "East China Sea via Yangtze Estuary"),
    # East China Sea
    ("East China Sea", "lat_range", "22°42'N-33°33'N"),
    ("East China Sea", "lon_range", "118°50'E-127°44'E"),
    ("East China Sea", "type", "marginal sea"),
    ("East China Sea", "north_coast", "Yangtze Estuary, Zhejiang"),
    ("East China Sea", "east_coast", "Kyushu, Ryukyu Islands"),
    ("East China Sea", "south_coast", "Fujian, Taiwan"),
    ("East China Sea", "connected_to", "South China Sea via Taiwan Strait"),
    ("East China Sea", "connected_to", "Yellow Sea via Yangtze Estuary"),
    # River Estuaries
    ("Yellow River Estuary", "lat_lon", "37°24'N, 118°52'E"),
    ("Yellow River Estuary", "location", "Dongying, Shandong"),
    ("Yellow River Estuary", "flows_into", "Bohai Sea"),
    ("Liao River Estuary", "lat_lon", "40°38'N, 121°53'E"),
    ("Liao River Estuary", "location", "Panjin, Liaoning"),
    ("Liao River Estuary", "flows_into", "Bohai Sea"),
    ("Yalu River Estuary", "lat_lon", "39°58'N, 124°15'E"),
    ("Yalu River Estuary", "location", "Dandong, Liaoning-Sinuiju, North Korea"),
    ("Yalu River Estuary", "flows_into", "Yellow Sea"),
    ("Huai River Estuary", "lat_lon", "33°07'N, 119°53'E"),
    ("Huai River Estuary", "location", "Huai'an, Jiangsu"),
    ("Huai River Estuary", "flows_into", "Yellow Sea"),
    ("Yangtze River Estuary", "lat_lon", "31°26'N, 121°13'E"),
    ("Yangtze River Estuary", "location", "Jiangsu-Shanghai border"),
    ("Yangtze River Estuary", "flows_into", "East China Sea"),
    ("Qiantang River Estuary", "lat_lon", "30°12'N, 120°52'E"),
    ("Qiantang River Estuary", "location", "Hangzhou, Zhejiang"),
    ("Qiantang River Estuary", "flows_into", "East China Sea"),
    ("Min River Estuary", "lat_lon", "26°00'N, 119°28'E"),
    ("Min River Estuary", "location", "Fuzhou, Fujian"),
    ("Min River Estuary", "flows_into", "East China Sea"),
    ("Pearl River Estuary", "lat_lon", "22°47'N, 113°36'E"),
    ("Pearl River Estuary", "location", "Guangzhou, Guangdong"),
    ("Pearl River Estuary", "flows_into", "South China Sea"),
    # Chl-a
    ("Chl-a", "related_to", "SST"),
    ("Chl-a", "higher_in", "moderate SST"),
    ("high_low_temp", "inhibits", "phytoplankton"),
    ("Chl-a", "related_to", "PIC"),
    ("PIC", "positively_correlated", "Chl-a"),
    ("high_nutrients", "promotes", "phytoplankton"),
    ("phytoplankton", "increases", "inorganic_carbon"),
    ("Chl-a", "related_to", "POC"),
    ("Chl-a", "positively_correlated", "POC"),
    ("phytoplankton", "affects", "organic_carbon"),
    ("Chl-a", "related_to", "PAR"),
    ("PAR", "drives", "phytoplankton_photosynthesis"),
    ("Chl-a", "positively_correlated", "PAR"),
    ("Chl-a", "related_to", "NFLH"),
    ("NFLH", "reflects", "Chl-a_fluorescence"),
    ("NFLH", "positively_correlated", "Chl-a"),
    ("high_Chl-a", "increases", "fluorescence"),
    # Spatial Distribution
    ("Chl-a", "higher_in", "coastal"),
    ("Chl-a", "decreases", "offshore"),
    ("Chl-a", "higher_in", "enclosed_seas"),
    ("Chl-a", "trend", "Bohai > Yellow Sea > East China Sea"),
    ("Yellow Sea", "high_Chl-a", "unique_water_env"),
    ("Bohai Sea", "rich_nutrients", "land_influence"),
    ("Bohai Sea", "high_Chl-a", "small_size"),
    ("East China Sea", "uniform_nutrients", "open_water"),
    ("East China Sea", "high_Chl-a", "southern_coast, Taiwan Strait"),
    ("Yellow River Estuary", "high_Chl-a", "rich_nutrients"),
    ("Yangtze River Estuary", "high_Chl-a", "rich_nutrients"),
    ("Pearl River Estuary", "high_Chl-a", "rich_nutrients"),
    # Other Elements
    ("SST", "influenced_by", "river_discharge, coastal_currents"),
    ("SST", "lower_in", "coastal"),
    ("SST", "higher_in", "offshore"),
    ("SST", "trend", "coast_to_offshore_increase"),
    ("PIC", "higher_in", "coastal"),
    ("PIC", "decreases", "offshore"),
    ("POC", "higher_in", "coastal"),
    ("POC", "decreases", "offshore"),
    ("PAR", "lower_in", "coastal"),
    ("PAR", "higher_in", "offshore"),
    ("NFLH", "stronger_in", "coastal"),
    ("NFLH", "weakens", "offshore"),
    ("marine_elements", "active_in", "coastal"),
    ("marine_elements", "decrease", "offshore"),
]
if __name__ == "__main__":
    print(len(spatial_triples))
    print(len(temporal_triples))
    print(len(myself_triples))
    # 将空间三元组导出为 Excel 文件
    spatial_df = pd.DataFrame(spatial_triples, columns=["头实体", "关系", "尾实体"])
    spatial_df.to_excel("spatial_triples.xlsx", index=False)

    # 将时间三元组导出为 Excel 文件
    temporal_df = pd.DataFrame(temporal_triples, columns=["头实体", "关系", "尾实体"])
    temporal_df.to_excel("temporal_triples.xlsx", index=False)

    #三元组导出为 Excel 文件
    myself_df = pd.DataFrame(myself_triples, columns=["头实体", "关系", "尾实体"])
    myself_df.to_excel("SKG_triples.xlsx", index=False)